export const apiRouters = {
  health: {
    check: "/health",
  },
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    logout: "/auth/logout",
    me: "/auth/me",
    tenantContext: "/auth/tenant/context",
  },
  system: {
    ready: "/ready",
    health: "/health",
  },
  rag: {
    knowledgeBases: {
      list: "/rag/knowledge-bases",
      create: "/rag/knowledge-bases",
      delete: "/rag/knowledge-bases/:id",
      decomposition: "/rag/knowledge-bases/:id/decomposition",
      decompositionDefaults: "/rag/knowledge-bases/:id/decomposition/defaults",
      planner: "/rag/knowledge-bases/:id/planner",
      plannerDefaults: "/rag/knowledge-bases/:id/planner/defaults",
      memoryConfig: "/rag/knowledge-bases/:id/memory-config",
      memoryConfigDefaults: "/rag/knowledge-bases/:id/memory-config/defaults",
      ingestionConfig: "/rag/knowledge-bases/:id/ingestion-config",
    },
    memory: {
      list: "/rag/memory",
      clear: "/rag/memory",
      deleteChunk: "/rag/memory/:chunkId",
    },
    modelProfiles: {
      list: "/rag/model-profiles",
      create: "/rag/model-profiles",
      delete: "/rag/model-profiles/:id",
    },
    indexProfiles: {
      list: "/rag/index-profiles",
      create: "/rag/index-profiles",
      activate: "/rag/index-profiles/:id/activate",
      retrieval: "/rag/index-profiles/:id/retrieval",
    },
    confidence: {
      config: "/confidence/config/:profileId",
      fixtures: "/confidence/fixtures",
      import: "/confidence/fixtures/import",
      generateSynthetic: "/confidence/fixtures/generate-synthetic",
      entries: "/confidence/fixtures/:fixtureId/entries",
      unlabeled: "/confidence/answer-runs/unlabeled",
      label: "/confidence/fixtures/:fixtureId/label",
      labelBulk: "/confidence/fixtures/:fixtureId/label-bulk",
      calibrate: "/confidence/calibrate/:profileId",
      calibrateStatus: "/confidence/calibrate/:jobId/status",
      threshold: "/confidence/models/:modelVersionId/threshold",
      promote: "/confidence/models/:modelVersionId/promote",
    },
    providerCredentials: {
      list: "/rag/provider-credentials",
      set: "/rag/provider-credentials",
      revoke: "/rag/provider-credentials/:provider/:keyName",
    },
    ingestion: {
      intake: "/rag/ingestion/intake",
      complete: "/rag/ingestion/complete",
      status: "/rag/ingestion/status/:documentVersionId",
      delete: "/rag/ingestion/:documentVersionId",
      documents: "/rag/ingestion/documents",
      parsedText: "/rag/ingestion/:versionId/parsed-text",
      approve: "/rag/ingestion/:versionId/approve",
      reject: "/rag/ingestion/:versionId/reject",
      pendingReviewCount: "/rag/ingestion/pending-review/count",
    },
    query: {
      ask: "/rag/query",
      trace: "/rag/query/traces/:traceId",
      feedback: "/rag/query/traces/:traceId/feedback",
    },
    mcp: {
      servers: "/rag/mcp/servers",
      server: "/rag/mcp/servers/:id",
      test: "/rag/mcp/servers/:id/test",
      discover: "/rag/mcp/servers/:id/discover",
      tools: "/rag/mcp/servers/:id/tools",
      tool: "/rag/mcp/tools/:id",
      invoke: "/rag/mcp/tools/:id/invoke",
      invocations: "/rag/mcp/invocations",
    },
  },
}
