from typing import Protocol

from app.domain.mcp.entities import McpCallResult, McpToolDescriptor


class McpClientAdapter(Protocol):
    async def connect(self) -> None: ...
    async def list_tools(self) -> list[McpToolDescriptor]: ...
    async def call_tool(self, name: str, arguments: dict[str, object]) -> McpCallResult: ...
    async def close(self) -> None: ...
