from datetime import datetime
from typing import Protocol

from app.domain.models import AuthSession, User, UserRole, UserStatus


class AuthRepository(Protocol):
    async def find_user_by_email(self, email: str) -> User | None: ...
    async def find_user_by_id(self, user_id: str) -> User | None: ...
    async def create_user(self, *, email: str, password_hash: str, name: str, role: UserRole, status: UserStatus, photo: str | None) -> User: ...
    async def create_auth_session(self, *, session_id: str, user_id: str, token_hash: str, expires_at: datetime) -> AuthSession: ...
    async def find_auth_session(self, session_id: str, user_id: str) -> AuthSession | None: ...
    async def delete_auth_session(self, session_id: str, user_id: str) -> None: ...
    async def delete_auth_sessions_for_user(self, user_id: str) -> None: ...
